### ISSUE TITLE
Firefox installation not possible

### ISSUE THREAD

**Issue by despecial** [Oktavilla/fontanello#2]
API says the addon code is corrupt.

Please fix

**Comment by frederfred** [comment]
Which OS and version of Firefox do you use?

**Comment by despecial** [comment]
Mac OS 10.13.3
FF 56.02

**Comment by frederfred** [comment]
Fontanello is built using the WebExtensions API, a cross-browser system for developing extensions. Firefox added support for the WebExtensions API in version 57, so in order to use Fontanello you need to upgrade Firefox.

Be aware that Firefox 57 dropped support for legacy add-ons. If you depend on any legacy add-on, I'm afraid you will have to live without Fontanello until those add-ons are migrated.
